Repository whynot-here/whynot-here-api-server, pull requests merged in 2022-04, with the labels that each got.

#70 [BE] fix: cors설정 누락 확인 및 수정
  src/main/java/handong/whynot/config/SecurityConfig.java
Labels: backend, bug, fix

#72 [BE] feat: fix application.yml
  log/app/deploy.log
  log/app/err_log.log
  src/main/java/handong/whynot/config/WebConfig.java
  src/main/resources/application.yml
Labels: backend, feature

#74 [BE] feat: 로그인/로그아웃 스펙 변경
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/dto/account/AccountResponseCode.java
  src/main/java/handong/whynot/dto/account/TokenCheckDTO.java
  src/main/java/handong/whynot/handler/CustomAuthenticationEntryPoint.java
  src/main/java/handong/whynot/handler/CustomLogoutSuccessHandler.java
  src/main/java/handong/whynot/handler/LoginFailureHandler.java
  src/main/java/handong/whynot/handler/LoginSuccessHandler.java
  src/main/resources/application-local.yml
Labels: backend, refactor

#76 [BE] feat: 로그인 상태 확인 API
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/config/WebConfig.java
  src/main/java/handong/whynot/dto/account/AccountResponseDTO.java
  src/main/java/handong/whynot/dto/account/IsLoginDTO.java
Labels: backend, feature

#77 feat: add API description
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/api/CommentController.java
  src/main/java/handong/whynot/api/JobController.java
  src/main/java/handong/whynot/api/PostController.java
  src/main/java/handong/whynot/api/S3Controller.java
Labels: backend, docs
