Repository whynot-here/whynot-here-api-server, pull requests merged in 2022-03, with the labels that each got.

#45 [BE] refactor: 이메일 인증 코드 8자리로 변경
  src/main/java/handong/whynot/domain/Account.java
  src/main/java/handong/whynot/service/AccountService.java
Labels: backend, refactor

#44 [BE] setting: 초기 데이터 sql 추가 및 unique 컬럼 설정
  src/main/java/handong/whynot/domain/JobPost.java
  src/main/java/handong/whynot/domain/PostApply.java
  src/main/java/handong/whynot/domain/PostFavorite.java
  src/main/resources/import.sql
Labels: backend, refactor

#54 [BE] refactor: response객체 수정
  src/main/java/handong/whynot/domain/Account.java
  src/main/java/handong/whynot/dto/account/AccountResponseDTO.java
  src/main/java/handong/whynot/dto/post/PostResponseDTO.java
  src/main/java/handong/whynot/service/PostService.java
  src/main/resources/application.yml
  src/main/resources/sql/schema.sql
  src/test/java/handong/whynot/service/PostServiceTest.java
Labels: backend, refactor, test

#55 [BE] feat: SwaggerConfig 추가 및 기타 관련 설정 수정
  build.gradle
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/api/JobController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/config/SwaggerConfig.java
  src/main/java/handong/whynot/exception/post/PostAlreadyApplyOff.java
  src/main/java/handong/whynot/util/ImageType.java
  src/main/resources/application.yml
Labels: backend, docs, feature, WIP

#57 [BE] 회원가입 form 검증 후 에러 반환 로직 리팩터링
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/handler/MethodArgumentNotValidExceptionHandler.java
  src/test/java/handong/whynot/api/AccountControllerTest.java
Labels: backend, feature, refactor

#58 [BE] build: dependency 업데이트
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: backend

#60 [BE] feat: 이메일 토큰 재전송 API 추가
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/dto/account/ResendTokenDTO.java
  src/main/java/handong/whynot/service/AccountService.java
Labels: backend, feature

#62 [BE] feat: logback 설정
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: backend, feature

#64 [BE] feat: auth 로직 변경 및 중복체크 API추가
  src/main/java/handong/whynot/api/AccountController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/dto/account/AccountResponseCode.java
  src/main/java/handong/whynot/dto/account/EmailDTO.java
  src/main/java/handong/whynot/dto/account/NicknameDTO.java
  src/main/java/handong/whynot/dto/post/PostResponseDTO.java
  src/main/java/handong/whynot/handler/AccountExceptionHandler.java
  src/main/java/handong/whynot/repository/AccountQueryRepository.java
  src/main/java/handong/whynot/service/AccountService.java
Labels: backend, feature

#69 [BE] 로그인 endpoint를 swagger에 노출
  build.gradle
  src/main/resources/application.yml
Labels: backend
