Repository whynot-here/whynot-here-api-server, pull requests merged in 2022-11, with the labels that each got.

#110 [BE] build: update dependencies
  build.gradle
Labels: backend

#108 [BE] test: v1 테스트 코드 제거
  src/test/java/handong/whynot/WhynotApplicationTests.java
  src/test/java/handong/whynot/api/AccountControllerTest.java
  src/test/java/handong/whynot/api/CommentControllerTest.java
  src/test/java/handong/whynot/api/PostControllerTest.java
  src/test/java/handong/whynot/api/v2/AccountControllerV2Test.java
  src/test/java/handong/whynot/common/WithMockCustomUser.java
  src/test/java/handong/whynot/common/WithMockCustomUserSecurityContextFactory.java
  src/test/java/handong/whynot/service/CommentServiceTest.java
  src/test/java/handong/whynot/service/PostServiceJpaTest.java
  src/test/java/handong/whynot/service/PostServiceTest.java
Labels: refactor, test

#109 [BE] refactor: 일부 코드 수정
  src/main/java/handong/whynot/api/v2/CategoryController.java
  src/main/java/handong/whynot/api/v2/CommentControllerV2.java
  src/main/java/handong/whynot/api/v2/PostControllerV2.java
  src/main/java/handong/whynot/domain/JobPost.java
  src/main/java/handong/whynot/domain/PostApply.java
  src/main/java/handong/whynot/domain/PostFavorite.java
  src/main/java/handong/whynot/dto/category/CategoryInfo.java
  src/main/java/handong/whynot/dto/comment/CommentResponseDTO.java
  src/main/java/handong/whynot/repository/PostFavoriteRepository.java
  src/main/java/handong/whynot/service/S3Service.java
Labels: refactor

#111 [BE] Redis cache 삭제 전략 수정
  src/main/java/handong/whynot/api/v2/PostControllerV2.java
  src/main/java/handong/whynot/service/PostService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
Labels: backend, refactor

#112 [BE] 후기 작성 API 추가
  src/main/java/handong/whynot/api/v2/AdminController.java
  src/main/java/handong/whynot/config/SecurityConfig.java
  src/main/java/handong/whynot/domain/UserFeedback.java
  src/main/java/handong/whynot/dto/admin/AdminResponseCode.java
  src/main/java/handong/whynot/dto/admin/UserFeedbackRequestDTO.java
  src/main/java/handong/whynot/handler/MethodArgumentNotValidExceptionHandler.java
  src/main/java/handong/whynot/repository/UserFeedbackRepository.java
  src/main/java/handong/whynot/service/UserFeedbackService.java
  src/main/resources/sql/schema.sql
Labels: backend, feature

#113 [BE] 공고 수정 API 버그 수정
  src/main/java/handong/whynot/domain/Post.java
  src/main/java/handong/whynot/service/PostService.java
Labels: backend, hotfix

#114 [BE] allowCredentials = true 변경
  src/main/java/handong/whynot/config/WebConfig.java
Labels: backend, hotfix

#115 [BE] 공고 조회 시 createdDt 내림차순 정렬
  build.gradle
  src/main/java/handong/whynot/api/v2/PostControllerV2.java
  src/main/java/handong/whynot/repository/PostQueryRepository.java
  src/main/java/handong/whynot/service/PostService.java
Labels: backend, refactor
